trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Dev
    jobs:
      - job: Build
        steps:
          - script: echo "Building..."

  - stage: Staging
    jobs:
      - job: Build
        steps:
          - script: echo "Building..."
      - job: Deploy
        dependsOn: Build
        steps:
          - script: echo "Deploying to Staging..."

  - stage: Prod
    jobs:
      - job: Build
        steps:
          - script: echo "Building..."
      - job: Deploy
        dependsOn: Build
        steps:
          - script: echo "Deploying to Prod..."
